Spiceypy Tutorial update
lulav/LRS_Documentation pull request #98
Opened 2023-12-15 11:26 UTC by gtep96

Requesting review

2023-12-18 12:31 UTC, mariaBer requested changes
All format and typos issues I changed myself

2023-12-18 12:31 UTC, mariaBer commented on docs_tutorials/spiceypy/spiceypy.md
> +## Scenario
Explain what the simulation will checking, 
See mass-spring damper/ pendulum scenarios as reference

2023-12-20 12:27 UTC, gtep96 commented
updated and pushed

2023-12-20 17:39 UTC, mariaBer commented on docs_tutorials/spiceypy/spiceypy.md
> +The output of the simulation comprises critical flight data, such as altitude, velocity, and other relevant parameters, recorded over time intervals. These results are published via ROS 2 topics, all
From the start until here, maybe better to move to the overview of the project? It again explains the project and not the scenario itself right? or atleast part of it can be moved or removed completely

2023-12-21 09:28 UTC, gtep96 commented on docs_tutorials/spiceypy/spiceypy.md
> +The output of the simulation comprises critical flight data, such as altitude, velocity, and other relevant parameters, recorded over time intervals. These results are published via ROS 2 topics, all
@mariaBer 
Hmm, i thought this is actually a description of scenario: it explains what does this scenario do (first sentence), it explains what inputs we will use for this scenario (second sentence) and gives a description for what we can get from it (third sentence). 

If you want to make it even shorter, i can suggest next text:

## Scenario
This simple scenario can be used to find the Cassini Spacecraft trajectory relative to Saturn's barycenter within specified time intervals. <br/>
Users can input the desired time bounds, and the output of the simulation will contain critical flight data, such as altitude, velocity, and other relevant parameters, recorded over time intervals. <br/>

Let me know is it OK/not Ok and i will add these changes

2023-12-21 11:09 UTC, mariaBer commented on docs_tutorials/spiceypy/spiceypy.md
> +The output of the simulation comprises critical flight data, such as altitude, velocity, and other relevant parameters, recorded over time intervals. These results are published via ROS 2 topics, all
It not the length that concerns me but the relevance.
The way you described it here is better, so yes, please change to this

2023-12-21 15:56 UTC, gtep96 commented on docs_tutorials/spiceypy/spiceypy.md
> +The output of the simulation comprises critical flight data, such as altitude, velocity, and other relevant parameters, recorded over time intervals. These results are published via ROS 2 topics, all
done

2023-12-21 15:56 UTC, gtep96 commented
done and pushed

2023-12-21 20:11 UTC, merged